"""Add tool_adapter_metrics column

Revision ID: b3177e90c798
Revises: bd219084aa0d
Create Date: 2025-05-29 10:19:42.210422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3177e90c798'
down_revision: Union[str, None] = 'bd219084aa0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth_profiles', sa.Column('tool_adapter_metrics', sa.Text(), nullable=True))
    op.create_index('idx_user_aad_object_id', 'user_auth_profiles', ['aad_object_id'], unique=False)
    op.create_index('idx_user_assigned_role', 'user_auth_profiles', ['assigned_role'], unique=False)
    op.create_index('idx_user_email', 'user_auth_profiles', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_email', table_name='user_auth_profiles')
    op.drop_index('idx_user_assigned_role', table_name='user_auth_profiles')
    op.drop_index('idx_user_aad_object_id', table_name='user_auth_profiles')
    op.drop_column('user_auth_profiles', 'tool_adapter_metrics')
    # ### end Alembic commands ###
